vim.keymap.set('n', 'er', function() remove() end)
vim.keymap.set('n', 'ef', function() wgo_to_note(vim.fn.expand([[<cword>]])) end)
vim.keymap.set('n', 'eu', function() wgo_to_note(vim.fn.expand([[%:p:h:h]])) end)
vim.keymap.set('n', 'ec', function() choose() end)
vim.keymap.set('n', 'en', function() rename() end)
vim.keymap.set('n', 'es', function() search_note(root) end)
vim.keymap.set('n', 'ea', function() add_extras() end)
vim.keymap.set('n', 'eo', function() remove_extras() end)
vim.keymap.set('n', 'eh', function() wgo_to_note(root) end)
vim.keymap.set('n', 'eb', function() go_back() end)
vim.keymap.set('n', 'el', function() link() end)
vim.keymap.set('n', 'els', function() search_note(vim.fn.expand([[%:p:h]])) end)
vim.keymap.set('n', 'evx', function() expand_note() end)
vim.keymap.set('n', 'evc', function() collapse_note() end)
vim.keymap.set('n', 'evax', function() expand_all_notes() end)
vim.keymap.set('n', 'evac', function() collapse_all_notes() end)
vim.keymap.set('n', 'etc', function() complete_task() end)
vim.keymap.set('n', 'etu', function() uncomplete_task() end)

vim.api.nvim_create_autocmd("BufRead", {command = "set syntax=markdown"})
vim.api.nvim_create_autocmd({"TextChanged", "TextChangedT", "ModeChanged"}, {callback = update_file})
vim.api.nvim_clear_autocmds({event = "TextChangedI"})
vim.api.nvim_create_autocmd({"ExitPre", "QuitPre"}, {callback = quit})
