vim.keymap.set('n', vinote_ld_key .. 'rm', function() remove() end)
vim.keymap.set('n', vinote_ld_key .. 'f', function() wgo_to_note(vim.fn.expand([[<cword>]])) end)
vim.keymap.set('n', vinote_ld_key .. 'u', function() wgo_to_note(vim.fn.expand([[%:p:h:h]])) end)
vim.keymap.set('n', vinote_ld_key .. 'c', function() choose() end)
vim.keymap.set('n', vinote_ld_key .. 'rn', function() rename() end)
vim.keymap.set('n', vinote_ld_key .. 'sn', function() search_note(root) end)
vim.keymap.set('n', vinote_ld_key .. 'h', function() wgo_to_note(root) end)
vim.keymap.set('n', vinote_ld_key .. 'b', function() go_back() end)
vim.keymap.set('n', vinote_ld_key .. 'l', function() link() end)
vim.keymap.set('n', vinote_ld_key .. 'ls', function() search_note(vim.fn.expand([[%:p:h]])) end)
vim.keymap.set('n', vinote_ld_key .. 'vx', function() expand_note() end)
vim.keymap.set('n', vinote_ld_key .. 'vc', function() collapse_note() end)
vim.keymap.set('n', vinote_ld_key .. 'vax', function() expand_all_notes() end)
vim.keymap.set('n', vinote_ld_key .. 'vac', function() collapse_all_notes() end)
vim.keymap.set('n', vinote_ld_key .. 'tc', function() complete_task() end)
vim.keymap.set('n', vinote_ld_key .. 'tu', function() uncomplete_task() end)
vim.keymap.set('n', vinote_ld_key .. 'sf', function() search_file() end)
vim.keymap.set('n', vinote_ld_key .. 'nn', function() horizontal_navigation(1) end)
vim.keymap.set('n', vinote_ld_key .. 'np', function() horizontal_navigation(-1) end)

vim.api.nvim_create_autocmd("BufRead", {command = "set syntax=markdown"})
vim.api.nvim_create_autocmd({"TextChanged", "TextChangedT", "ModeChanged"}, {callback = update_file})
vim.api.nvim_clear_autocmds({event = "TextChangedI"})
vim.api.nvim_create_autocmd({"ExitPre", "QuitPre"}, {callback = quit})
